on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

name: CI
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        if: success()
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -short ./...

  race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        if: success()
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v2
      - name: Run tests with race detector
        run: go test -race -short ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        if: success()
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v2
      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
